### ISSUE TITLE
gTTS Option Support

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/apg_flask#11]
When [apg support becomes available](https://github.com/jeffwright13/audio_program_generator/issues/13#issue-917175821), open up options with html

**Comment by jeffwright13** [comment]
APG now passes in an arbitrary number of keyword arguments (as **kwargs) in addition to its two positional arguments (phrase_file and sound_file). So any underlying gTTS options are now supported.

**Comment by bbelderbos** [comment]
Cool, do you handle new kwargs though? I remember we only popped "slow" and "attenuation" off manually ...
